<a href="https://colab.research.google.com/github/marcelostaub/google_colab_testes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [2]:
# criando um array
d = [1,2,3,4,5,6]
arr = np.array(d)
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
# checar tipo
arr.dtype

dtype('int64')

In [4]:
# verificando o formato
np.shape(arr)

(6,)

In [6]:
# Get number of elements
np.size(arr)

6

In [6]:
d2 = [[1,3,5,7], [3,55,6,90]]
arr1 =np.array(d2)
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [8]:
np.shape(arr1)

(2, 4)

In [9]:
# consultar um elemento pela linha e coluna [l, c]
arr1[1,2]

np.int64(6)

In [10]:
# Retornar determinada linha do array
arr1[0, :]

array([1, 3, 5, 7])

In [11]:
arr1[1, :]

array([ 3, 55,  6, 90])

In [12]:
# retornar um intervalo de elementos
arr1[1, 1:3]

array([55,  6])

In [13]:
# inicialização de array
np.empty(6, dtype='int32')

array([         0,          0,          0, 1071644672,          0,
       1072693248], dtype=int32)

In [14]:
np.empty([2,2], dtype='int32')

array([[ 522263980,  -83376167],
       [1667943201,  476637065]], dtype=int32)

In [4]:
# criar matriz 3x3 com números entre 0 e 57
np.random.randint(0,57, size=(3,3))

array([[17, 38,  8],
       [21, 54, 23],
       [32, 12, 25]])

======= Operações Matemáticas ============

In [7]:
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [8]:
arr3 = arr1 * 2
arr3

array([[  2,   6,  10,  14],
       [  6, 110,  12, 180]])

In [9]:
arr4 = arr1 / 2
arr4

array([[ 0.5,  1.5,  2.5,  3.5],
       [ 1.5, 27.5,  3. , 45. ]])

In [10]:
arr5 = arr1 + 2
arr5

array([[ 3,  5,  7,  9],
       [ 5, 57,  8, 92]])

In [13]:
subarr = np.subtract(arr4, arr1)
subarr

array([[ -0.5,  -1.5,  -2.5,  -3.5],
       [ -1.5, -27.5,  -3. , -45. ]])

In [14]:
# média de toda a matriz
arr1.mean()

np.float64(21.25)

In [15]:
# soma acumulada de determinado eixo
arr1.cumsum(axis=1)

array([[  1,   4,   9,  16],
       [  3,  58,  64, 154]])

======= Transformações de Arrays ============

In [16]:
# criar array com função arange
arr4 = np.arange(8)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
# reshape: altera a estrutura da matriz (linhas, colunas)
arr5 = arr4.reshape(4,2)
arr5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [18]:
arr6 = arr5.reshape(2,4)
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
# obter a matriz transposta
arr7 = arr6.T
arr7

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [20]:
# concatenar matrizes
arr8 = np.concatenate((arr5, arr7))
arr8

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [21]:
# split: dividir um array em mais arrays
np.split(arr7, 2)

[array([[0, 4],
        [1, 5]]),
 array([[2, 6],
        [3, 7]])]

# importar um array de um arquivo:
arr9 = np.genfromtxt('array.txt', delimiter=',')