<a href="https://colab.research.google.com/github/marcelostaub/google_colab_testes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [2]:
# criando um array
d = [1,2,3,4,5,6]
arr = np.array(d)
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
# checar tipo
arr.dtype

dtype('int64')

In [4]:
# verificando o formato
np.shape(arr)

(6,)

In [6]:
# Get number of elements
np.size(arr)

6

In [7]:
d2 = [[1,3,5,7], [3,55,6,90]]
arr1 =np.array(d2)
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [8]:
np.shape(arr1)

(2, 4)

In [9]:
# consultar um elemento pela linha e coluna [l, c]
arr1[1,2]

np.int64(6)

In [10]:
# Retornar determinada linha do array
arr1[0, :]

array([1, 3, 5, 7])

In [11]:
arr1[1, :]

array([ 3, 55,  6, 90])

In [12]:
# retornar um intervalo de elementos
arr1[1, 1:3]

array([55,  6])

In [13]:
# inicialização de array
np.empty(6, dtype='int32')

array([         0,          0,          0, 1071644672,          0,
       1072693248], dtype=int32)

In [14]:
np.empty([2,2], dtype='int32')

array([[ 522263980,  -83376167],
       [1667943201,  476637065]], dtype=int32)

In [4]:
# criar matriz 3x3 com números entre 0 e 57
np.random.randint(0,57, size=(3,3))

array([[17, 38,  8],
       [21, 54, 23],
       [32, 12, 25]])